/// <reference types='./globals.d.ts' />
/* tslint:disable */
/* eslint-disable */
/**
 * 系统管理 - version
 *
 *
 *
 * OpenAPI version: 3.0.1
 *
 *
 * NOTE: This file is auto generated by the alova's vscode plugin.
 *
 * https://alova.js.org/devtools/vscode
 *
 * **Do not edit the file manually.**
 */
export default {
  'Diagnose.get_diagnose_list': ['GET', '/diagnose/list'],
  'DiagSub.get_diagsub_getdiaglist': ['GET', '/diagSub/getDiagList'],
  'DiagSub.get_diagsub_getdiagsubpagelist': ['GET', '/diagSub/getDiagSubPageList'],
  'DiagSub.get_diagsub_getdiagsubinfo': ['GET', '/diagSub/getDiagSubInfo'],
  'DiagSub.post_diagsub_savediagsubinfo': ['POST', '/diagSub/saveDiagSubInfo'],
  'DiagSub.post_diagsub_deletediagsubinfo': ['POST', '/diagSub/deleteDiagSubInfo'],
  'DiagSub.post_diagsub_downloadtemplate': ['POST', '/diagSub/downloadTemplate'],
  'DiagSub.post_diagsub_importdiagsubinfo': ['POST', '/diagSub/importDiagSubInfo'],
  'Evaluation.get_evaluation_getevaluationlist': ['GET', '/evaluation/getEvaluationList'],
  'Evaluation.get_evaluation_getevaluationdetail': ['GET', '/evaluation/getEvaluationDetail'],
  'Evaluation.post_evaluation_setevaluationstatus': ['POST', '/evaluation/setEvaluationStatus'],
  'Evaluation.post_evaluation_deleteevaluation': ['POST', '/evaluation/deleteEvaluation'],
  'Evaluation.post_evaluation_saveevaluation': ['POST', '/evaluation/saveEvaluation'],
  'RecoveryScale.get_recoveryscale_getrecoveryscalelist': ['GET', '/recoveryScale/getRecoveryScaleList'],
  'RecoveryScale.get_recoveryscale_getrecoveryscaledetail': ['GET', '/recoveryScale/getRecoveryScaleDetail'],
  'RecoveryScale.post_recoveryscale_setrecoveryscalestatus': ['POST', '/recoveryScale/setRecoveryScaleStatus'],
  'RecoveryScale.post_recoveryscale_deleterecoveryscale': ['POST', '/recoveryScale/deleteRecoveryScale'],
  'RecoveryScale.post_recoveryscale_saverecoveryscale': ['POST', '/recoveryScale/saveRecoveryScale'],
  'RecoveryScale.get_recoveryscale_getrecoveryscalebinddiaglist': [
    'GET',
    '/recoveryScale/getRecoveryScaleBindDiagList'
  ],
  'RecoveryScale.post_recoveryscale_saverecoveryscalebinddiag': ['POST', '/recoveryScale/saveRecoveryScaleBindDiag'],
  'Rule.get_rule_getlist': ['GET', '/rule/getList'],
  'Rule.get_rule_get': ['GET', '/rule/get'],
  'Rule.post_rule_post': ['POST', '/rule/post'],
  'Rule.post_rule_postenabled': ['POST', '/rule/postEnabled'],
  'Rule.post_rule_postdelete': ['POST', '/rule/postDelete'],
  'SysDictionary.get_sysdictionary_getalllist': ['GET', '/sysDictionary/getAllList'],
  'SysDictionary.post_sysdictionary_adddictionary': ['POST', '/sysDictionary/addDictionary'],
  'SysDictionary.post_sysdictionary_updatedictionary': ['POST', '/sysDictionary/updateDictionary'],
  'SysDictionary.get_sysdictionary_getdictionarydetail': ['GET', '/sysDictionary/getDictionaryDetail'],
  'SysDictionary.post_sysdictionary_dictionaryopration': ['POST', '/sysDictionary/dictionaryOpration'],
  'SysDictionary.get_sysdictionary_getitempagelist': ['GET', '/sysDictionary/getItemPageList'],
  'SysDictionary.get_sysdictionary_getitemalllist': ['GET', '/sysDictionary/getItemAllList'],
  'SysDictionary.post_sysdictionary_adddictionaryitem': ['POST', '/sysDictionary/addDictionaryItem'],
  'SysDictionary.post_sysdictionary_updatedictionaryitem': ['POST', '/SysDictionary/updateDictionaryItem'],
  'SysDictionary.get_sysdictionary_getdictionaryitemdetail': ['GET', '/SysDictionary/getDictionaryItemDetail'],
  'SysDictionary.post_sysdictionary_dictionaryitemopration': ['POST', '/SysDictionary/dictionaryItemOpration'],
  'SysOrganization.get_sysorganization_getorganizationpagelist': ['GET', '/sysOrganization/getOrganizationPageList'],
  'SysOrganization.get_sysorganization_getorganizationinfo': ['GET', '/sysOrganization/getOrganizationInfo'],
  'SysOrganization.post_sysorganization_saveorganization': ['POST', '/sysOrganization/saveOrganization'],
  'SysOrganization.post_sysorganization_deleteorganization': ['POST', '/sysOrganization/deleteOrganization'],
  'SysOrganization.get_sysorganization_getorganizationuserlist': ['GET', '/sysOrganization/getOrganizationUserList'],
  'SysOrganization.post_sysorganization_saveorganizationuser': ['POST', '/sysOrganization/saveOrganizationUser'],
  'SysOrganization.get_sysorganization_getdepartmentsource': ['GET', '/sysOrganization/getDepartmentSource'],
  'SysOrganization.get_sysorganization_getuserpagelist': ['GET', '/sysOrganization/getUserPageList'],
  'SysOrganization.get_sysorganization_getorganizationlistbyuserid': [
    'GET',
    '/sysOrganization/getOrganizationListByUserID'
  ],
  'SysOrganization.get_sysorganization_getnurselist': ['GET', '/sysOrganization/getNurseList'],
  'SysOrganization.get_sysorganization_getnursesource': ['GET', '/sysOrganization/getNurseSource'],
  'SysOrganization.get_sysorganization_getnurseinfo': ['GET', '/sysOrganization/getNurseInfo'],
  'SysOrganization.post_sysorganization_operationnurse': ['POST', '/sysOrganization/operationNurse'],
  'SysOrganization.post_sysorganization_savenurse': ['POST', '/sysOrganization/saveNurse'],
  'SysParams.get_sysparams_getparamslist': ['GET', '/sysParams/getParamsList'],
  'SysParams.get_sysparams_getparamsinfo': ['GET', '/sysParams/getParamsInfo'],
  'SysParams.get_sysparams_getgroupsource': ['GET', '/sysParams/getGroupSource'],
  'SysParams.post_sysparams_saveparamsinfo': ['POST', '/sysParams/saveParamsInfo'],
  'SysParams.post_sysparams_operation': ['POST', '/sysParams/operation'],
  'SysParams.get_sysparams_getsysparamconfigpreviewinfo': ['GET', '/sysParams/getSysParamConfigPreviewInfo'],
  'SysParams.get_sysparams_getconfigvalue': ['GET', '/sysParams/getConfigValue'],
  'SysParams.post_sysparams_setconfigvalue': ['POST', '/sysParams/setConfigValue'],
  'SysPWRule.get_syspwrule_getrulesource': ['GET', '/sysPWRule/getRuleSource'],
  'SysPWRule.post_syspwrule_savepasswordrule': ['POST', '/sysPWRule/savePassWordRule'],
  'SysReportTreatCategory.get_sysreporttreatcategory_gettreatcategorylist': [
    'GET',
    '/sysReportTreatCategory/getTreatCategoryList'
  ],
  'SysReportTreatCategory.get_sysreporttreatcategory_gettreatcategoryinfo': [
    'GET',
    '/sysReportTreatCategory/getTreatCategoryInfo'
  ],
  'SysReportTreatCategory.post_sysreporttreatcategory_deletetreatcategory': [
    'POST',
    '/sysReportTreatCategory/deleteTreatCategory'
  ],
  'SysReportTreatCategory.post_sysreporttreatcategory_savetreatcategory': [
    'POST',
    '/sysReportTreatCategory/saveTreatCategory'
  ],
  'SysSettingGroup.get_syssettinggroup_getgrouplist': ['GET', '/sysSettingGroup/getGroupList'],
  'SysSettingGroup.get_syssettinggroup_getgroupinfo': ['GET', '/sysSettingGroup/getGroupInfo'],
  'SysSettingGroup.post_syssettinggroup_savegroupinfo': ['POST', '/sysSettingGroup/saveGroupInfo'],
  'SysSettingGroup.post_syssettinggroup_operation': ['POST', '/sysSettingGroup/operation'],
  'SysTeam.get_systeam_getsysteamtree': ['GET', '/sysTeam/getSysTeamTree'],
  'SysTeam.get_systeam_getsysteamuserlist': ['GET', '/sysTeam/getSysTeamUserList'],
  'SysTeam.post_systeam_setsysteamleader': ['POST', '/sysTeam/setSysTeamLeader'],
  'SysTeam.post_systeam_cancelsysteamleader': ['POST', '/sysTeam/cancelSysTeamLeader'],
  'SysTeam.get_systeam_getteamdetail': ['GET', '/sysTeam/getTeamDetail'],
  'SysTeam.post_systeam_saveteam': ['POST', '/sysTeam/saveTeam'],
  'SysTeam.post_systeam_deleteteam': ['POST', '/sysTeam/deleteTeam'],
  'SysTeam.post_systeam_saveteamuser': ['POST', '/sysTeam/saveTeamUser'],
  'SysTeam.post_systeam_deleteteamuser': ['POST', '/sysTeam/deleteTeamUser'],
  'SysTeam.get_systeam_getbindteamuserlist': ['GET', '/sysTeam/getBindTeamUserList'],
  'SysTeam.get_systeam_getteamlist': ['GET', '/sysTeam/getTeamList'],
  'SysTeam.get_systeam_getteaminfobyuser': ['GET', '/sysTeam/getTeamInfoByUser'],
  'SysTeamTreatItem.get_systeamtreatitem_getteambindtreatitemlist': [
    'GET',
    '/sysTeamTreatItem/getTeamBindTreatItemList'
  ],
  'SysTeamTreatItem.post_systeamtreatitem_saveteambindtreatitem': ['POST', '/sysTeamTreatItem/saveTeamBindTreatItem'],
  'SysTeamTreatItem.post_systeamtreatitem_copyteamtreatitem': ['POST', '/sysTeamTreatItem/copyTeamTreatItem'],
  'SysTreatItem.get_systreatitems_getsystreatitemlist': ['GET', '/sysTreatItems/getSysTreatItemList'],
  'SysTreatItem.get_systreatitems_gettreatitemlist': ['GET', '/sysTreatItems/getTreatItemList'],
  'SysTreatItem.get_systreatitems_getsystreatitemdetail': ['GET', '/sysTreatItems/getSysTreatItemDetail'],
  'SysTreatItem.post_systreatitems_savesystreatitem': ['POST', '/sysTreatItems/saveSysTreatItem'],
  'SysTreatItem.post_systreatitems_setsystreatitemstatus': ['POST', '/sysTreatItems/setSysTreatItemStatus'],
  'SysTreatItem.post_systreatitems_savesystreatitemcategory': ['POST', '/sysTreatItems/saveSysTreatItemCategory'],
  'SysTreatItem.get_systreatitems_getevaluationselectitemlist': ['GET', '/sysTreatItems/getEvaluationSelectItemList'],
  'SysTreatItem.post_systreatitems_saveevaluationselectitem': ['POST', '/sysTreatItems/saveEvaluationSelectItem'],
  'SysTreatItem.get_systreatitems_getpointlist': ['GET', '/sysTreatItems/getPointList'],
  'SysTreatItem.post_systreatitems_savepointlatest': ['POST', '/sysTreatItems/savePointLatest'],
  'SysUserTreatItem.get_sysusertreatitem_getsysdeptusertree': ['GET', '/sysUserTreatItem/getSysDeptUserTree'],
  'SysUserTreatItem.get_sysusertreatitem_getuserbindtreatitemlist': [
    'GET',
    '/sysUserTreatItem/getUserBindTreatItemList'
  ],
  'SysUserTreatItem.get_sysusertreatitem_getuserlist': ['GET', '/sysUserTreatItem/getUserList'],
  'SysUserTreatItem.post_sysusertreatitem_saveuserbindtreatitem': ['POST', '/sysUserTreatItem/saveUserBindTreatItem'],
  'SysUserTreatItem.post_sysusertreatitem_copyuserbindtreatitem': ['POST', '/sysUserTreatItem/copyUserBindTreatItem'],
  'SysWFStepDefine.get_sysworkflow_getstepdefinelist': ['GET', '/sysWorkFlow/getStepDefineList'],
  'SysWFStepDefine.get_sysworkflow_getstepdefineinfo': ['GET', '/sysWorkFlow/getStepDefineInfo'],
  'SysWFStepDefine.post_sysworkflow_savestepdefineinfo': ['POST', '/SysWorkFlow/SaveStepDefineInfo'],
  'SysWFStepDefine.post_sysworkflow_stepdefineoperation': ['POST', '/sysWorkFlow/stepDefineOperation'],
  'SysWFStepDefine.get_sysworkflow_getuserlist': ['GET', '/sysWorkFlow/getUserList'],
  'SysWFStepDefine.get_sysworkflow_getrolelist': ['GET', '/sysWorkFlow/getRoleList'],
  'SysWFStepDefine.get_sysworkflow_getpermissionsource': ['GET', '/sysWorkFlow/getPermissionSource'],
  'SysWFStepDefine.get_sysworkflow_getdeptsource': ['GET', '/sysWorkFlow/getDeptSource'],
  'SysWorkFlow.get_sysworkflow_getmainconfiglist': ['GET', '/sysWorkFlow/getMainConfigList'],
  'SysWorkFlow.get_sysworkflow_getmainconfiginfo': ['GET', '/sysWorkFlow/getMainConfigInfo'],
  'SysWorkFlow.get_sysworkflow_getmainconfig': ['GET', '/sysWorkFlow/getMainConfig'],
  'SysWorkFlow.post_sysworkflow_savemainconfiginfo': ['POST', '/sysWorkFlow/saveMainConfigInfo'],
  'SysWorkFlow.post_sysworkflow_savemainconfig': ['POST', '/sysWorkFlow/saveMainConfig'],
  'SysWorkFlow.post_sysworkflow_savemainconfigoperation': ['POST', '/sysWorkFlow/saveMainConfigOperation'],
  'SysWorkFlow.get_sysworkflow_getconditiondefinelist': ['GET', '/sysWorkFlow/getConditionDefineList'],
  'SysWorkFlow.get_sysworkflow_getconditiondefineinfo': ['GET', '/sysWorkFlow/getConditionDefineInfo'],
  'SysWorkFlow.post_sysworkflow_saveconditiondefineinfo': ['POST', '/sysWorkFlow/saveConditionDefineInfo'],
  'SysWorkFlow.post_sysworkflow_conditiondefineoperation': ['POST', '/sysWorkFlow/conditionDefineOperation'],
  'TreatEquipMent.get_treatequipment_gettreatequipmentlist': ['GET', '/treatEquipMent/getTreatEquipMentList'],
  'TreatEquipMent.get_treatequipment_gettreatequipmentinfo': ['GET', '/treatEquipMent/getTreatEquipMentInfo'],
  'TreatEquipMent.post_treatequipment_savetreatequipment': ['POST', '/treatEquipMent/saveTreatEquipMent'],
  'TreatEquipMent.post_treatequipment_operatetreatequipment': ['POST', '/treatEquipMent/operateTreatEquipMent'],
  'TreatEquipMent.get_treatequipment_getequipmenttypeitemlist': ['GET', '/treatEquipMent/getEquipMentTypeItemList'],
  'TreatEquipMent.post_treatequipment_saveequipmenttypeitem': ['POST', '/treatEquipMent/saveEquipMentTypeItem'],
  'TreatEquipMent.post_treatequipment_gettreatequipmentrecordlist': [
    'POST',
    '/treatEquipMent/getTreatEquipMentRecordList'
  ],
  'TreatFileTemplate.get_filetemplate_getlist': ['GET', '/fileTemplate/getList'],
  'TreatFileTemplate.get_filetemplate_getdetail': ['GET', '/fileTemplate/getDetail'],
  'TreatFileTemplate.post_filetemplate_enabletemplate': ['POST', '/fileTemplate/enableTemplate'],
  'TreatFileTemplate.post_filetemplate_deletetemplate': ['POST', '/fileTemplate/deleteTemplate'],
  'TreatFileTemplate.post_filetemplate_savetemplate': ['POST', '/fileTemplate/saveTemplate'],
  'TreatFileTemplate.get_filetemplate_getitemlink': ['GET', '/fileTemplate/getItemLink'],
  'TreatFileTemplate.post_filetemplate_saveitemlink': ['POST', '/fileTemplate/saveItemLink'],
  'TreatItemPoint.get_treatitempoint_getitemlist': ['GET', '/treatItemPoint/getItemList'],
  'TreatItemPoint.get_treatitempoint_getpointvaluelist': ['GET', '/treatItemPoint/getPointValueList'],
  'TreatItemPoint.post_treatitempoint_savepointvalue': ['POST', '/treatItemPoint/savePointValue'],
  'TreatItemPoint.post_treatitempoint_import': ['POST', '/treatItemPoint/import'],
  'TreatItemPoint.get_treatitempoint_export': ['GET', '/treatItemPoint/export']
};
