/// <reference types='./globals.d.ts' />
/* tslint:disable */
/* eslint-disable */
/**
 * ABP框架 - version
 *
 *
 *
 * OpenAPI version: 3.0.1
 *
 *
 * NOTE: This file is auto generated by the alova's vscode plugin.
 *
 * https://alova.js.org/devtools/vscode
 *
 * **Do not edit the file manually.**
 */
export default {
  'System.get_system_gettime': ['GET', '/system/getTime'],
  'UserAccount.get_useraccount_init': ['GET', '/userAccount/init'],
  'UserAccount.get_useraccount_gethospitallist': ['GET', '/userAccount/getHospitalList'],
  'UserAccount.get_useraccount_getpwvalidate': ['GET', '/userAccount/getPWValidate'],
  'UserAccount.post_useraccount_login': ['POST', '/userAccount/login'],
  'UserAccount.get_useraccount_getuserinfo': ['GET', '/userAccount/getUserInfo'],
  'UserAccount.post_useraccount_wechatlogin': ['POST', '/userAccount/weChatLogin'],
  'UserAccount.post_useraccount_getwxuserinfo': ['POST', '/userAccount/getWxUserInfo'],
  'UserAccount.post_useraccount_refreshtoken': ['POST', '/userAccount/refreshToken'],
  'UserAccount.get_useraccount_logout': ['GET', '/userAccount/logout'],
  'UserAccount.post_useraccount_ssoauth': ['POST', '/userAccount/ssoAuth'],
  'UserAccount.post_useraccount_ssologin': ['POST', '/userAccount/ssoLogin'],
  'UserAccount.post_useraccount_platformlogin': ['POST', '/userAccount/platformLogin']
};
