/* tslint:disable */
/* eslint-disable */
/**
 * ABP框架 - version
 *
 *
 *
 * OpenAPI version: 3.0.1
 *
 *
 * NOTE: This file is auto generated by the alova's vscode plugin.
 *
 * https://alova.js.org/devtools/vscode
 *
 * **Do not edit the file manually.**
 */
import type { Alova, AlovaMethodCreateConfig, AlovaGenerics, Method } from 'alova';
import type { $$userConfigMap, alovaInstance } from '.';
import type apiDefinitions from './apiDefinitions';

type CollapsedAlova = typeof alovaInstance;
type UserMethodConfigMap = typeof $$userConfigMap;

type Alova2MethodConfig<Responded> =
  CollapsedAlova extends Alova<
    AlovaGenerics<
      any,
      any,
      infer RequestConfig,
      infer Response,
      infer ResponseHeader,
      infer L1Cache,
      infer L2Cache,
      infer SE
    >
  >
    ? Omit<
        AlovaMethodCreateConfig<
          AlovaGenerics<Responded, any, RequestConfig, Response, ResponseHeader, L1Cache, L2Cache, SE>,
          any,
          Responded
        >,
        'params'
      >
    : never;

// Extract the return type of transform function that define in $$userConfigMap, if it not exists, use the default type.
type ExtractUserDefinedTransformed<
  DefinitionKey extends keyof typeof apiDefinitions,
  Default
> = DefinitionKey extends keyof UserMethodConfigMap
  ? UserMethodConfigMap[DefinitionKey]['transform'] extends (...args: any[]) => any
    ? Awaited<ReturnType<UserMethodConfigMap[DefinitionKey]['transform']>>
    : Default
  : Default;
type Alova2Method<
  Responded,
  DefinitionKey extends keyof typeof apiDefinitions,
  CurrentConfig extends Alova2MethodConfig<any>
> =
  CollapsedAlova extends Alova<
    AlovaGenerics<
      any,
      any,
      infer RequestConfig,
      infer Response,
      infer ResponseHeader,
      infer L1Cache,
      infer L2Cache,
      infer SE
    >
  >
    ? Method<
        AlovaGenerics<
          CurrentConfig extends undefined
            ? ExtractUserDefinedTransformed<DefinitionKey, Responded>
            : CurrentConfig['transform'] extends (...args: any[]) => any
              ? Awaited<ReturnType<CurrentConfig['transform']>>
              : ExtractUserDefinedTransformed<DefinitionKey, Responded>,
          any,
          RequestConfig,
          Response,
          ResponseHeader,
          L1Cache,
          L2Cache,
          SE
        >
      >
    : never;

export type InitOutput = {
  /**
   * 加密方式
   * -1=不加密，0=仅加密入参，1=仅加密出参，2=出参入参都加密
   */
  encryptWay?: number;
  /**
   * 公钥
   */
  publicKey?: string;
};
export type BaseOutput_IDName = {
  /**
   * id
   */
  id?: string;
  /**
   * 名称
   */
  name?: string;
};
export type GetPWValidateOutPut = {
  /**
   * 正则表达式
   */
  regular?: string;
  /**
   * 提示语
   */
  message?: string;
};
export type LoginResultEnum = 0 | 1 | 2 | 3 | 4 | 5;
export type LoginResultDto = {
  result?: LoginResultEnum;
  /**
   * 是否需要验证码
   */
  needVerifyCode?: boolean;
  /**
   * 登录失败次数
   */
  failCount?: number;
  /**
   * 剩余可登录次数
   */
  remainCount?: number;
  /**
   * 访问令牌
   */
  token?: string;
  /**
   * 刷新令牌
   */
  refreshToken?: string;
  name?: string;
  /**
   * 用户ID
   */
  userId?: string;
  /**
   * 用户名称
   */
  userName?: string;
  /**
   * 头像
   */
  avator?: string;
  /**
   * 性别
   */
  sex?: string;
  /**
   * 登录机构ID
   */
  loginOrganizationId?: string;
  /**
   * 所属机构ID
   */
  organizationId?: string;
};
export type LoginInput = {
  /**
   * 手机号/用户名
   * [required]
   */
  userName: string;
  /**
   * 密码
   * [required]
   */
  password: string;
  /**
   * 登录机构
   * [required]
   */
  organizationId: string;
  /**
   * 登录类型
   */
  deviceType?: string;
};
export type LoginRole = {
  /**
   * 角色名称
   */
  roleName?: string;
  /**
   * 角色编码
   */
  value?: string;
};
export type LoginPermission = {
  /**
   * 权限ID
   */
  id?: string;
  /**
   * 父ID
   */
  parentID?: string;
  /**
   * 权限编码
   */
  code?: string;
  /**
   * 权限名称
   */
  name?: string;
  /**
   * 类型
   */
  type?: number;
  /**
   * 地址
   */
  url?: string;
  /**
   * 图标
   */
  icon?: string;
  /**
   * 排序
   */
  sort?: number;
  /**
   * 重定向地址
   */
  redirect?: string;
  /**
   * 是否缓存
   */
  isCache?: boolean;
  /**
   * 组件地址
   */
  component?: string;
  /**
   * 是否固定
   */
  isAffix?: boolean;
  /**
   * 是否隐藏
   */
  hidden?: boolean;
  /**
   * 是否白名单
   */
  isWhiteList?: boolean;
};
export type LoginUserInfoOutput = {
  /**
   * 用户Id
   */
  userId?: string;
  /**
   * 账号名称
   */
  username?: string;
  /**
   * 部门ID
   */
  deptID?: string;
  /**
   * 部门名称
   */
  deptName?: string;
  /**
   * 机构Id
   */
  organID?: string;
  /**
   * 机构名称
   */
  organName?: string;
  /**
   * 密码有效性
   */
  editPasswordStatus?: number;
  /**
   * 修改密码验证方式
   */
  editPasswordVerifyWay?: number;
  /**
   * 角色集合
   */
  roles?: LoginRole[];
  /**
   * 权限集合
   */
  permission?: LoginPermission[];
  /**
   * 默认首页编码
   */
  homepageCode?: string;
  /**
   * 账号
   */
  loginID?: string;
  /**
   * 手机号码
   */
  mobilePhone?: string;
  /**
   * 密码
   */
  password?: string;
  /**
   * 是否显示辅助人
   */
  isShowNurse?: boolean;
  /**
   * 是否显示治疗时间
   */
  isShowTreatTime?: boolean;
};
export type WeChatLoginOutput = {
  /**
   * 令牌
   */
  token?: string;
  /**
   * 授权结果
   * 0=代表首次授权，前端跳转到【首页】，1=代表之前已经授权过，直接跳转到【用户点餐页面】
   */
  result?: number;
  /**
   * openID
   */
  openID?: string;
};
export type WeChatLoginInput = {
  /**
   * 微信授权码
   */
  code?: string;
  /**
   * 微信OpenID
   */
  openID?: string;
  /**
   * 机构ID
   * [required]
   */
  organID: string;
};
export type WxUserInfoModel = {
  /**
   * 账户ID
   */
  id?: string;
  /**
   * 账户名称
   */
  userName?: string;
};
export type GetWxUserInfoOutput = {
  wxUserInfo?: WxUserInfoModel;
  /**
   * 授权结果
   * 0=代表首次授权，1=代表之前已经授权过
   */
  result?: number;
};
export type WeChatUserInfoModel = {
  /**
   * 头像
   */
  image?: string;
  /**
   * 性别
   */
  sex?: number;
  /**
   * 姓名
   */
  userName?: string;
};
export type WeChatPatientInfoModel = {
  /**
   * 患者ID
   */
  patientID?: string;
  /**
   * 就诊卡号
   */
  hospitalID?: string;
  /**
   * 是否默认
   */
  isDefault?: boolean;
};
export type GetWxUserInfoInput = {
  weChatUserInfo?: WeChatUserInfoModel;
  weChatPatientInfo?: WeChatPatientInfoModel;
  /**
   * 微信openID
   */
  openID?: string;
  /**
   * 是否更新患者信息
   */
  isUpdatePatient?: boolean;
};
export type TokenOutput = {
  accessToken?: string;
  refreshToken?: string;
};
export type TokenInput = {
  refreshToken?: string;
};
export type SsoAuthInput = {
  /**
   * LoginId
   * [required]
   */
  loginId: string;
  /**
   * 院区id
   * [required]
   */
  hospitalId: string;
};
export type SsoLoginInput = {
  /**
   * LoginId
   */
  loginId?: string;
};
export type PlatformLoginInput = {
  /**
   * 工号 对应用户表的loginID
   * [required]
   */
  userID: string;
  /**
   * 科室ID
   */
  deptID?: string;
  /**
   * 凭据
   * [required]
   */
  ticket: string;
};
declare global {
  interface userApis {
    System: {
      /**
       * ---
       *
       * [GET] 获取系统时间
       *
       * **path:** /system/getTime
       *
       * ---
       *
       * **Response**
       * ```ts
       * type Response = string
       * ```
       */
      get_system_gettime<Config extends Alova2MethodConfig<string>>(
        config?: Config
      ): Alova2Method<string, 'System.get_system_gettime', Config>;
    };
    UserAccount: {
      /**
       * ---
       *
       * [GET] 初始化系统
       *
       * **path:** /userAccount/init
       *
       * ---
       *
       * **Response**
       * ```ts
       * type Response = {
       *   // 加密方式
       *   // -1=不加密，0=仅加密入参，1=仅加密出参，2=出参入参都加密
       *   encryptWay?: number
       *   // 公钥
       *   publicKey?: string
       * }
       * ```
       */
      get_useraccount_init<Config extends Alova2MethodConfig<InitOutput>>(
        config?: Config
      ): Alova2Method<InitOutput, 'UserAccount.get_useraccount_init', Config>;
      /**
       * ---
       *
       * [GET] 获取用户的院区
       *
       * **path:** /userAccount/getHospitalList
       *
       * ---
       *
       * **Query Parameters**
       * ```ts
       * type QueryParameters = {
       *   // [required]
       *   loginID: string
       * }
       * ```
       *
       * ---
       *
       * **Response**
       * ```ts
       * type Response = Array<{
       *   // id
       *   id?: string
       *   // 名称
       *   name?: string
       * }>
       * ```
       */
      get_useraccount_gethospitallist<
        Config extends Alova2MethodConfig<BaseOutput_IDName[]> & {
          params: {
            /**
             * [required]
             */
            loginID: string;
          };
        }
      >(
        config: Config
      ): Alova2Method<BaseOutput_IDName[], 'UserAccount.get_useraccount_gethospitallist', Config>;
      /**
       * ---
       *
       * [GET] 获取密码正则
       *
       * **path:** /userAccount/getPWValidate
       *
       * ---
       *
       * **Response**
       * ```ts
       * type Response = {
       *   // 正则表达式
       *   regular?: string
       *   // 提示语
       *   message?: string
       * }
       * ```
       */
      get_useraccount_getpwvalidate<Config extends Alova2MethodConfig<GetPWValidateOutPut>>(
        config?: Config
      ): Alova2Method<GetPWValidateOutPut, 'UserAccount.get_useraccount_getpwvalidate', Config>;
      /**
       * ---
       *
       * [POST] 用户登录
       *
       * **path:** /userAccount/login
       *
       * ---
       *
       * **RequestBody**
       * ```ts
       * type RequestBody = {
       *   // 手机号/用户名
       *   // [required]
       *   userName: string
       *   // 密码
       *   // [required]
       *   password: string
       *   // 登录机构
       *   // [required]
       *   organizationId: string
       *   // 登录类型
       *   deviceType?: string
       * }
       * ```
       *
       * ---
       *
       * **Response**
       * ```ts
       * type Response = {
       *   result?: 0 | 1 | 2 | 3 | 4 | 5
       *   // 是否需要验证码
       *   needVerifyCode?: boolean
       *   // 登录失败次数
       *   failCount?: number
       *   // 剩余可登录次数
       *   remainCount?: number
       *   // 访问令牌
       *   token?: string
       *   // 刷新令牌
       *   refreshToken?: string
       *   name?: string
       *   // 用户ID
       *   userId?: string
       *   // 用户名称
       *   userName?: string
       *   // 头像
       *   avator?: string
       *   // 性别
       *   sex?: string
       *   // 登录机构ID
       *   loginOrganizationId?: string
       *   // 所属机构ID
       *   organizationId?: string
       * }
       * ```
       */
      post_useraccount_login<
        Config extends Alova2MethodConfig<LoginResultDto> & {
          data: LoginInput;
        }
      >(
        config: Config
      ): Alova2Method<LoginResultDto, 'UserAccount.post_useraccount_login', Config>;
      /**
       * ---
       *
       * [GET] 获取用户信息
       *
       * **path:** /userAccount/getUserInfo
       *
       * ---
       *
       * **Response**
       * ```ts
       * type Response = {
       *   // 用户Id
       *   userId?: string
       *   // 账号名称
       *   username?: string
       *   // 部门ID
       *   deptID?: string
       *   // 部门名称
       *   deptName?: string
       *   // 机构Id
       *   organID?: string
       *   // 机构名称
       *   organName?: string
       *   // 密码有效性
       *   editPasswordStatus?: number
       *   // 修改密码验证方式
       *   editPasswordVerifyWay?: number
       *   // 角色集合
       *   roles?: Array<{
       *     // 角色名称
       *     roleName?: string
       *     // 角色编码
       *     value?: string
       *   }>
       *   // 权限集合
       *   permission?: Array<{
       *     // 权限ID
       *     id?: string
       *     // 父ID
       *     parentID?: string
       *     // 权限编码
       *     code?: string
       *     // 权限名称
       *     name?: string
       *     // 类型
       *     type?: number
       *     // 地址
       *     url?: string
       *     // 图标
       *     icon?: string
       *     // 排序
       *     sort?: number
       *     // 重定向地址
       *     redirect?: string
       *     // 是否缓存
       *     isCache?: boolean
       *     // 组件地址
       *     component?: string
       *     // 是否固定
       *     isAffix?: boolean
       *     // 是否隐藏
       *     hidden?: boolean
       *     // 是否白名单
       *     isWhiteList?: boolean
       *   }>
       *   // 默认首页编码
       *   homepageCode?: string
       *   // 账号
       *   loginID?: string
       *   // 手机号码
       *   mobilePhone?: string
       *   // 密码
       *   password?: string
       *   // 是否显示辅助人
       *   isShowNurse?: boolean
       *   // 是否显示治疗时间
       *   isShowTreatTime?: boolean
       * }
       * ```
       */
      get_useraccount_getuserinfo<Config extends Alova2MethodConfig<LoginUserInfoOutput>>(
        config?: Config
      ): Alova2Method<LoginUserInfoOutput, 'UserAccount.get_useraccount_getuserinfo', Config>;
      /**
       * ---
       *
       * [POST] 微信扫码授权登录
       *
       * **path:** /userAccount/weChatLogin
       *
       * ---
       *
       * **RequestBody**
       * ```ts
       * type RequestBody = {
       *   // 微信授权码
       *   code?: string
       *   // 微信OpenID
       *   openID?: string
       *   // 机构ID
       *   // [required]
       *   organID: string
       * }
       * ```
       *
       * ---
       *
       * **Response**
       * ```ts
       * type Response = {
       *   // 令牌
       *   token?: string
       *   // 授权结果
       *   // 0=代表首次授权，前端跳转到【首页】，1=代表之前已经授权过，直接跳转到【用户点餐页面】
       *   result?: number
       *   // openID
       *   openID?: string
       * }
       * ```
       */
      post_useraccount_wechatlogin<
        Config extends Alova2MethodConfig<WeChatLoginOutput> & {
          data: WeChatLoginInput;
        }
      >(
        config: Config
      ): Alova2Method<WeChatLoginOutput, 'UserAccount.post_useraccount_wechatlogin', Config>;
      /**
       * ---
       *
       * [POST] 获取微信账户信息（该接口客户端不调用，仅供服务端调用）
       *
       * **path:** /userAccount/getWxUserInfo
       *
       * ---
       *
       * **RequestBody**
       * ```ts
       * type RequestBody = {
       *   weChatUserInfo?: {
       *     // 头像
       *     image?: string
       *     // 性别
       *     sex?: number
       *     // 姓名
       *     userName?: string
       *   }
       *   weChatPatientInfo?: {
       *     // 患者ID
       *     patientID?: string
       *     // 就诊卡号
       *     hospitalID?: string
       *     // 是否默认
       *     isDefault?: boolean
       *   }
       *   // 微信openID
       *   openID?: string
       *   // 是否更新患者信息
       *   isUpdatePatient?: boolean
       * }
       * ```
       *
       * ---
       *
       * **Response**
       * ```ts
       * type Response = {
       *   wxUserInfo?: {
       *     // 账户ID
       *     id?: string
       *     // 账户名称
       *     userName?: string
       *   }
       *   // 授权结果
       *   // 0=代表首次授权，1=代表之前已经授权过
       *   result?: number
       * }
       * ```
       */
      post_useraccount_getwxuserinfo<
        Config extends Alova2MethodConfig<GetWxUserInfoOutput> & {
          data: GetWxUserInfoInput;
        }
      >(
        config: Config
      ): Alova2Method<GetWxUserInfoOutput, 'UserAccount.post_useraccount_getwxuserinfo', Config>;
      /**
       * ---
       *
       * [POST] 刷新token(获取新的accessToken)
       *
       * **path:** /userAccount/refreshToken
       *
       * ---
       *
       * **RequestBody**
       * ```ts
       * type RequestBody = {
       *   refreshToken?: string
       * }
       * ```
       *
       * ---
       *
       * **Response**
       * ```ts
       * type Response = {
       *   accessToken?: string
       *   refreshToken?: string
       * }
       * ```
       */
      post_useraccount_refreshtoken<
        Config extends Alova2MethodConfig<TokenOutput> & {
          data: TokenInput;
        }
      >(
        config: Config
      ): Alova2Method<TokenOutput, 'UserAccount.post_useraccount_refreshtoken', Config>;
      /**
       * ---
       *
       * [GET] 退出系统
       *
       * **path:** /userAccount/logout
       *
       * ---
       *
       * **Response**
       * ```ts
       * type Response = unknown
       * ```
       */
      get_useraccount_logout<Config extends Alova2MethodConfig<unknown>>(
        config?: Config
      ): Alova2Method<unknown, 'UserAccount.get_useraccount_logout', Config>;
      /**
       * ---
       *
       * [POST] 康复系统获取授权Code
       *
       * **path:** /userAccount/ssoAuth
       *
       * ---
       *
       * **RequestBody**
       * ```ts
       * type RequestBody = {
       *   // LoginId
       *   // [required]
       *   loginId: string
       *   // 院区id
       *   // [required]
       *   hospitalId: string
       * }
       * ```
       *
       * ---
       *
       * **Response**
       * ```ts
       * type Response = string
       * ```
       */
      post_useraccount_ssoauth<
        Config extends Alova2MethodConfig<string> & {
          data: SsoAuthInput;
        }
      >(
        config: Config
      ): Alova2Method<string, 'UserAccount.post_useraccount_ssoauth', Config>;
      /**
       * ---
       *
       * [POST] 康复系统单点登录
       *
       * **path:** /userAccount/ssoLogin
       *
       * ---
       *
       * **RequestBody**
       * ```ts
       * type RequestBody = {
       *   // LoginId
       *   loginId?: string
       * }
       * ```
       *
       * ---
       *
       * **Response**
       * ```ts
       * type Response = {
       *   accessToken?: string
       *   refreshToken?: string
       * }
       * ```
       */
      post_useraccount_ssologin<
        Config extends Alova2MethodConfig<TokenOutput> & {
          data: SsoLoginInput;
        }
      >(
        config: Config
      ): Alova2Method<TokenOutput, 'UserAccount.post_useraccount_ssologin', Config>;
      /**
       * ---
       *
       * [POST] 集成平台单点登录
       *
       * **path:** /userAccount/platformLogin
       *
       * ---
       *
       * **RequestBody**
       * ```ts
       * type RequestBody = {
       *   // 工号 对应用户表的loginID
       *   // [required]
       *   userID: string
       *   // 科室ID
       *   deptID?: string
       *   // 凭据
       *   // [required]
       *   ticket: string
       * }
       * ```
       *
       * ---
       *
       * **Response**
       * ```ts
       * type Response = string
       * ```
       */
      post_useraccount_platformlogin<
        Config extends Alova2MethodConfig<string> & {
          data: PlatformLoginInput;
        }
      >(
        config: Config
      ): Alova2Method<string, 'UserAccount.post_useraccount_platformlogin', Config>;
    };
  }

  var userApis: userApis;
}
